# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

production:
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
  reset_stale_sending_drafts:
    class: ResetStaleSendingDraftsJob
    schedule: every 5 minutes
  commitfest_daily_import:
    command: "system('ruby', Rails.root.join('script', 'commitfest_import.rb').to_s)"
    schedule: every day at 3am
  stats_daily_rebuild:
    command: "system('ruby', Rails.root.join('script', 'build_stats.rb').to_s)"
    schedule: every day at 4am
  assemble_topic_summary_batches:
    class: AssembleTopicSummaryBatchJob
    schedule: every 15 minutes
  poll_topic_summary_batches:
    class: PollTopicSummaryBatchesJob
    schedule: every 15 minutes

development:
  assemble_topic_summary_batches:
    class: AssembleTopicSummaryBatchJob
    schedule: every 15 minutes
  poll_topic_summary_batches:
    class: PollTopicSummaryBatchesJob
    schedule: every 15 minutes
